debug: true
logging:
  level: "DEBUG"
registry:
  auto_register: true
  auto_discover: true
  included_configs:
  - "./src/ember/core/registry/model/providers/openai/openai_config.yaml"
  - "./src/ember/core/registry/model/providers/anthropic/anthropic_config.yaml"
  - "./src/ember/core/registry/model/providers/deepmind/gemini_config.yaml"
  # Optional local overrides may be provided under "models:"
  # To add more providers here as we grow