registry:
  models:
    - id: "anthropic:claude-3.5-sonnet"
      name: "claude-3.5-sonnet-latest"
      cost:
        input_cost_per_thousand: 3
        output_cost_per_thousand: 15
      rate_limit:
        tokens_per_minute: 300000
        requests_per_minute: 2000
      provider:
        name: "Anthropic"
        default_api_key: "${ANTHROPIC_API_KEY}"
        base_url: "https://api.anthropic.com"
      api_key: null